export const products = [
  { id: 1, title: "AeroFlex Oversized Graphic Tee", price: 29.99, description: "Heavy cotton street tee with dropped shoulders, puff-print artwork, and a washed charcoal finish for an everyday layered fit.", category: "clothing", image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.7, count: 184 } },
  { id: 2, title: "MetroLine Cargo Joggers", price: 54.0, description: "Tapered utility joggers with zip pockets, stretch waistband, and a clean technical silhouette built for city wear.", category: "clothing", image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.6, count: 126 } },
  { id: 3, title: "Northbound Puffer Jacket", price: 89.5, description: "Lightweight insulated puffer with matte shell fabric, storm collar, and a roomy fit that works from commute to weekend travel.", category: "outerwear", image: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.8, count: 214 } },
  { id: 4, title: "Studio Knit Co-ord Hoodie", price: 61.99, description: "Soft brushed hoodie designed for a matching set look with rib trims, tonal drawcords, and a premium relaxed drape.", category: "clothing", image: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.5, count: 91 } },
  { id: 5, title: "Summit Trail Running Shoes", price: 96.0, description: "Responsive foam runners with a grippy outsole, breathable mesh upper, and reinforced heel support for long active days.", category: "shoes", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.9, count: 302 } },
  { id: 6, title: "Orbit Retro Sneakers", price: 78.5, description: "Low-profile sneakers with vintage paneling, cushioned insoles, and neutral tones that pair easily with denim or cargos.", category: "shoes", image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.7, count: 267 } },
  { id: 7, title: "Canvas Court Trainers", price: 49.99, description: "Minimal lace-up trainers with textured rubber soles and a clean canvas build for an easy everyday rotation.", category: "shoes", image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.4, count: 138 } },
  { id: 8, title: "Luna Leather Chelsea Boots", price: 112.0, description: "Polished pull-on boots with elastic side panels, stacked heel, and a versatile profile that sharpens casual fits.", category: "shoes", image: "https://images.unsplash.com/photo-1608256246200-53e8b47b2f80?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.8, count: 118 } },
  { id: 9, title: "Weekender Duffel Bag", price: 65.0, description: "Structured duffel with coated canvas, interior tech sleeve, and removable shoulder strap for short trips or gym carry.", category: "bags", image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.6, count: 84 } },
  { id: 10, title: "Transit Crossbody Sling", price: 38.99, description: "Compact everyday sling with quick-access front compartment, hidden back pocket, and adjustable woven strap.", category: "bags", image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.5, count: 72 } },
  { id: 11, title: "Apex Polarized Sunglasses", price: 34.5, description: "Modern square-frame sunglasses with lightweight arms, polarized lenses, and subtle matte hardware detailing.", category: "accessories", image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.3, count: 109 } },
  { id: 12, title: "Core Beanie Pack", price: 24.0, description: "Rib-knit beanie in an all-season gauge with fold-over cuff and soft touch finish for cooler evenings.", category: "accessories", image: "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.2, count: 64 } },
  { id: 13, title: "Heritage Denim Jacket", price: 72.0, description: "Structured denim jacket with contrast stitch work, metal shanks, and a timeless mid-blue wash for daily layering.", category: "outerwear", image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.7, count: 153 } },
  { id: 14, title: "CloudSoft Lounge Set", price: 58.0, description: "Matching lounge set with ultra-soft knit fabrication, boxy top, and relaxed shorts made for comfort-first styling.", category: "clothing", image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.6, count: 95 } },
  { id: 15, title: "Motion Zip Performance Jacket", price: 67.5, description: "Athleisure zip jacket with moisture-managing fabric, subtle reflective trim, and thumbhole cuffs for active use.", category: "activewear", image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.5, count: 132 } },
  { id: 16, title: "Stride Performance Shorts", price: 32.99, description: "Breathable training shorts with split hem mobility, secure zip pocket, and a lightweight liner for movement.", category: "activewear", image: "https://images.unsplash.com/photo-1506629905607-d9db835e70e4?auto=format&fit=crop&w=900&q=80", rating: { rate: 4.4, count: 87 } }
];
